name: taxi_app_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  url_launcher: ^6.3.2
  lottie_screen_onboarding_flutter: ^1.1.3
  lottie: ^3.3.2
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.3.5
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Profile.png
    - assets/animations/car_loading.json
    - assets/images/logo.png
